nhap/config/routes.rb
Rails.application.routes.draw do
#  get 'comment/create'

  #get '/blogs', to: 'blogs#index'
  resources :blogs, only: [:index, :new, :create,
  :show, :edit, :update,:destroy] do
      resources :comments, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/hello',to: 'hello#index'
  post '/hello',to: 'hello#say_hello'
end

nhap/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

nhap/app/models/blog.rb
 class Blog < ApplicationRecord
   validates :title, presence: true
   validates :content, presence: true

   has_many :comments
end

nhap/app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :blog
end

nhap/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#  protect_from_forgery with: :exception
end

nhap/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end
  def create
    @article = Blog.create(article_params)
    unless(@article.save)
      flash[:error] = "Error: Cannot create new article"
      render 'new'
    else
      redirect_to blogs_path
    end
  end

  def new
    @article = Blog.new
  end
  def show
    @article = Blog.find(params[:id])
    @comment = Comment.new
  end
  def edit
    @article = Blog.find(params[:id])
  end

  def update
    article = Blog.find(params[:id])
  #  article.title = params[:blog][:title]
  #  article.content = params[:blog][:content]
    if(article.update(article_params).present?)
      redirect_to blog_path(params[:id])
    else
      render 'edit'
    end
  end

  def destroy
    @article = Blog.find(params[:id])
    @article.destroy
  redirect_to blogs_path

  end



  def article_params
    params.require(:blog).permit(:title, :content)
  end

end

nhap/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(comment_params)
    comment.blog_id =  params[:blog_id]

    if comment.save
      redirect_to blog_path(params[:blog_id])
    else
      flash[:error] = "Can not create new comment"
      redirect_to blog_path(params[:blog_id])
    end

  end

  private
  def comment_params
    params.require(:comment).permit(:name, :content)
  end
end

nhap/app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
    @name = 'default'
  end
  def say_hello
    @name =params[:name]
    render 'index'
  end
end

nhap/app/helpers/application_helper.rb
module ApplicationHelper
end

nhap/app/helpers/blogs_helper.rb
module BlogsHelper
end

nhap/app/helpers/comment_helper.rb
module CommentHelper
end

nhap/app/helpers/hello_helper.rb
module HelloHelper
end

nhap/app/views/blogs/_form.html.erb
<%= form_for @article do |f|  %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control',
    placeholder: 'Enter your article title' %><br />
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control',
     placeholder: 'Enter your article content'%><br />
  </div>
  <%= f.submit class: 'btn btn-primary'%>
<% end %>

nhap/app/views/blogs/edit.html.erb
<%= render"form" %>

nhap/app/views/blogs/index.html.erb
<div class="container">
  <div class="row">
    <h1 class="page-header">Article Index</h1>
  </div>
  <div class="row">
    <%= link_to 'New Blog', new_blog_path,
    class: 'btn btn-danger'%>
  </div>
  <div class="row">
    <table class="table">
      <tr>
        <th>#</th>
        <th>title</th>
        <th>content</th>
        <th>created at</th>
        <th>updated at</th>
        <th> action </th>
      </tr>
      <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.id %></td>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= blog.created_at %></td>
        <td><%= blog.updated_at %></td>
        <td>
          <%= link_to "Show", blog_path(blog.id)  %> |
          <%= link_to "Edit", edit_blog_path(blog.id)  %> |
          <%= link_to 'Destroy', blog_path(blog.id),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

nhap/app/views/blogs/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="page-header">Article Index</h1>
  </div>
<div class="row">
  <% if(flash[:error])  %>
  <div class="alert alert-danger" role="alert">
    <strong>Error</strong> <%= flash[:error] %>
  </div>
  <% end %>
</div>
<div class="row">
  <%= render"form" %>
</div>
</div>

nhap/app/views/blogs/show.html.erb
title: <%= @article.title %> </br>
content : <%= @article.content %></br>


<% if(flash[:error])  %>
  <%= flash[:error] %>
<% end %>

<%= form_for [@article, @comment] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <br>
  <%= f.button %>
<% end %>

<% if @article.comments.count == 0 %>
  <strong> No Comments </strong>
<% else %>

  Number of comments: <%= @article.comments.count %>
  <br/>
  <strong >Comments: </strong>
  <ul>
    <% @article.comments.each do |comment| %>
    <li><%= comment.id %> - <%=comment.content %> </li>
    <% end %>
</ul>
<% end %>
content : <%= @article.content %>

nhap/app/views/comment/create.html.erb
<h1>Comment#create</h1>
<p>Find me in app/views/comment/create.html.erb</p>

nhap/app/views/hello/index.html.erb
<form action="/hello" method="post">
  name: <input type="text" name="name" id="name" value="<%= @name %>"/> <br/>
  <button type="submit">Say Hello</button>
</form>
Hello <%= @name%>

nhap/app/views/hello/say_hello.html.erb
Hello <%= @name%>  

nhap/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nhap</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper container-fluid">
      <div class="header row">
        <div class="col-md-12">
          <nav class="navbar navbar-light bg-faded">
            <a class="navbar-brand" href="#">Blog Application By Nho and Quoc</a>
            <ul class="nav navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">

                <%= link_to  "Hello", hello_path, class: 'nav-link' %>
              <!--  <a class="nav-link" href="#">Say Hello</a> -->
              </li>
              <li class="nav-item">
                <%= link_to "Aritcles", blogs_path, class: 'nav-link' %>
              <!--  <a class="nav-link" href="/blogs">Article</a> -->
              </li>

            </ul>
           </nav>
        </div>
      </div>
      <div class="content row">
        <div class="sidebar col-md-3">
          side bar
        </div>
        <div class="main-content col-md-9 ">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>